The following line threw a AttributeError exception: 'HMM' object has no attribute 'tag':
ttags = model.tag(s)
-------
The following line threw a NameError exception: name 'ttags' is not defined:
print("Tagged a trial sentence:\n  %s"%list(zip(s,ttags)))
-------
The following line threw a AttributeError exception: 'HMM' object has no attribute 'get_viterbi_value':
v_sample=model.get_viterbi_value('VERB',5)
-------
The following lines threw a NameError exception: name 'v_sample' is not defined:
if not (type(v_sample)==float and 0.0<=v_sample):
       print('viterbi value (%s) must be a cost'%v_sample,file=sys.stderr)
-------
The following line threw a AttributeError exception: 'HMM' object has no attribute 'get_backpointer_value':
b_sample=model.get_backpointer_value('VERB',5)
-------
The following lines threw a NameError exception: name 'b_sample' is not defined:
if not (type(b_sample)==str and b_sample in model.states):
       print('backpointer value (%s) must be a state name'%b_sample,file=sys.stderr)
-------
The following lines threw a AttributeError exception: 'HMM' object has no attribute 'tag':
for sentence in test_data_universal:
    s = [word.lower() for (word, tag) in sentence]
    model.initialise(s[0])
    tags = model.tag(s)
    for ((word,gold),tag) in zip(sentence,tags):
        if tag == gold:
            correct+=1
        else:
            incorrect+=1
-------
The following line threw a ZeroDivisionError exception: float division by zero:
accuracy = 1.0*correct/(correct+incorrect)
-------
The following line threw a NameError exception: name 'accuracy' is not defined:
print('Tagging accuracy for test set of %s sentences: %.4f'%(test_size,accuracy))
-------
The following line threw a NotImplementedError exception: answer_question4b:
bad_tags, good_tags, answer4b = answer_question4b()
-------
The following line threw a NameError exception: name 'bad_tags' is not defined:
print(bad_tags)
-------
The following line threw a NameError exception: name 'good_tags' is not defined:
print(good_tags)
-------
The following line threw a NameError exception: name 'answer4b' is not defined:
print(answer4b[:280])
-------
The following line threw a NotImplementedError exception: answer_question5:
answer5=answer_question5()
-------
The following line threw a NameError exception: name 'answer5' is not defined:
print(answer5[:500])
-------
The following line threw a NotImplementedError exception: answer_question6:
answer6=answer_question6()
-------
The following line threw a NameError exception: name 'answer6' is not defined:
print(answer6[:500])
-------
Exception in answer dict value computation:
    accuracy -> NameError("name 'accuracy' is not defined",)
  File "/Users/adelina/Desktop/assignment2-cor/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
Exception in answer dict value computation:
    bad_tags -> NameError("name 'bad_tags' is not defined",)
  File "/Users/adelina/Desktop/assignment2-cor/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
Exception in answer dict value computation:
    good_tags -> NameError("name 'good_tags' is not defined",)
  File "/Users/adelina/Desktop/assignment2-cor/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
Exception in answer dict value computation:
    answer4b -> NameError("name 'answer4b' is not defined",)
  File "/Users/adelina/Desktop/assignment2-cor/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
Exception in answer dict value computation:
    model.get_viterbi_value("VERB",5) -> AttributeError("'HMM' object has no attribute 'get_viterbi_value'",)
  File "/Users/adelina/Desktop/assignment2-cor/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
Exception in answer dict value computation:
    min((model.get_viterbi_value(s,-1) for s in model.states)) if len(model.states)>0 else FAILED -> AttributeError("'HMM' object has no attribute 'get_viterbi_value'",)
  File "/Users/adelina/Desktop/assignment2-cor/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <genexpr>
Exception in answer dict value computation:
    list(ttags) -> NameError("name 'ttags' is not defined",)
  File "/Users/adelina/Desktop/assignment2-cor/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
Exception in answer dict value computation:
    answer5 -> NameError("name 'answer5' is not defined",)
  File "/Users/adelina/Desktop/assignment2-cor/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
Exception in answer dict value computation:
    answer6 -> NameError("name 'answer6' is not defined",)
  File "/Users/adelina/Desktop/assignment2-cor/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
Exception in answer dict value computation:
    model.get_viterbi_value("VERB",0) -> AttributeError("'HMM' object has no attribute 'get_viterbi_value'",)
  File "/Users/adelina/Desktop/assignment2-cor/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
Exception in answer dict value computation:
    model.get_backpointer_value("VERB",0) -> AttributeError("'HMM' object has no attribute 'get_backpointer_value'",)
  File "/Users/adelina/Desktop/assignment2-cor/autodrive_embed.py", line 55, in safeEval
    return eval(expr,gdict)
  File "<string>", line 1, in <module>
